version: '3.7'

services:
  frontend:
    build:
      context: './frontend'
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/code
      - /code/node_modules
    command: npm run start
    ports: 
      - 3000:3000
  backend:
    build:
      context: './backend'
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/code
      - /code/node_modules
    command: npm start
    ports: 
      - 8000:8000
    depends_on: 
      - db
  db:
    image: mongo
    restart: always
    logging: 
      driver: none
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"