version: '3.8'

services:
  frontend:
    build:
      context: './frontend'
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/code
      - /frontend/node_modules
    command: npm run start
    ports:
      - 3000
  backend:
    build:
      context: './backend'
      dockerfile: ./Dockerfile
    depends_on: 
      - mongo
    volumes:
      - ./backend:/code
      - /backend/node_modules
    command: npm run start
    ports:
      - 8833
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  proxy:
    image: tivix/docker-nginx:v9
    environment:
      - UPSTREAMS=/:frontend:3000,/api:backend:8833
    depends_on:
      - backend
    ports:
      - '8088:80'